# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vie-en-Yoga
author:
  name: Ora Josey-Hay
  url: https://www.vie-en-yoga.com/
email: centre.vie.en.yoga@free.fr
phone:
  landline: 04.76.71.63.07
  mobile: 06.18.10.81.34
description: >- # this means to ignore newlines until "baseurl:"
  Cours et stages de Yoga à Grenoble, pour tous de débutant à confirmé.
  Ora Josef-Hay, 30 ans d'expérience du Hatha Yoga.
  Le centre propose aussi yoga pour séniors, PMR ou personne en situation de handicap.
keywords:
  - cours
  - yoga
  - grenoble
  - stages
url: "https://www.vie-en-yoga.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
lang: fr

google_analytics: G-G4470NEK6E

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

date_format: "%d/%m/%Y"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
