name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.213.0
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Check generated HTML pages
        run: |
          bundle exec jekyll build && \
          bundle exec htmlproofer \
            --only-4xx \
            --check-internal-hash=false \
            --enforce-https=false \
            ./_site
